//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Mrv.Regatta.Waage.Db.DataModels
{
	/// <summary>
	/// Database       : Daten
	/// Data Source    : C:\regatta\Daten.mdb
	/// Server Version : 04.00.0000
	/// </summary>
	public partial class DatenDB : LinqToDB.Data.DataConnection
	{
		public ITable<ATRennen>             ATRennens             { get { return this.GetTable<ATRennen>(); } }
		public ITable<AVereinNaman>         AVereinNamen          { get { return this.GetTable<AVereinNaman>(); } }
		public ITable<Einfügefehler>        Einfügefehler         { get { return this.GetTable<Einfügefehler>(); } }
		public ITable<TAbmeldung>           TAbmeldungs           { get { return this.GetTable<TAbmeldung>(); } }
		public ITable<TAbteilungstext>      TAbteilungstexts      { get { return this.GetTable<TAbteilungstext>(); } }
		public ITable<TAltersklassen>       TAltersklassens       { get { return this.GetTable<TAltersklassen>(); } }
		public ITable<TAltersklassenzusatz> TAltersklassenzusatzs { get { return this.GetTable<TAltersklassenzusatz>(); } }
		public ITable<TBoote>               TBootes               { get { return this.GetTable<TBoote>(); } }
		public ITable<TBootsklasse>         TBootsklasses         { get { return this.GetTable<TBootsklasse>(); } }
		public ITable<TGewichtsklassen>     TGewichtsklassens     { get { return this.GetTable<TGewichtsklassen>(); } }
		public ITable<TIndize>              TIndizes              { get { return this.GetTable<TIndize>(); } }
		public ITable<TLänder>              TLänder               { get { return this.GetTable<TLänder>(); } }
		public ITable<TLauftyptext>         TLauftyptexts         { get { return this.GetTable<TLauftyptext>(); } }
		public ITable<TRennen>              TRennens              { get { return this.GetTable<TRennen>(); } }
		public ITable<TRuderer>             TRuderers             { get { return this.GetTable<TRuderer>(); } }
		public ITable<TTest_deleteme>       TTest_deleteme        { get { return this.GetTable<TTest_deleteme>(); } }
		public ITable<TVerein>              TVereins              { get { return this.GetTable<TVerein>(); } }

		public DatenDB()
		{
			InitDataContext();
		}

		public DatenDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	// View
	[Table("ATRennen")]
	public partial class ATRennen
	{
		[Identity             ] public int       Index                  { get; set; } // Long
		[Column,      Nullable] public int?      RRF                    { get; set; } // Long
		[Column,      Nullable] public string    RNr                    { get; set; } // text(6)
		[Column,      Nullable] public string    RKBez                  { get; set; } // text(50)
		[Column,      Nullable] public string    RLBez                  { get; set; } // text(75)
		[Column,      Nullable] public string    RLänge                 { get; set; } // text(6)
		[Column,      Nullable] public byte?     RStartplaetze          { get; set; } // Byte
		[Column,      Nullable] public decimal?  RMeldGeld              { get; set; } // Currency
		[Column,      Nullable] public DateTime? RZeit                  { get; set; } // DateTime
		[Column,      Nullable] public string    RTag                   { get; set; } // text(2)
		[Column,      Nullable] public short?    RBootAnz               { get; set; } // Short
		[Column,   NotNull    ] public bool      RNotProtokoll          { get; set; } // Bit
		[Column,      Nullable] public string    RSpenden               { get; set; } // text(250)
		[Column,      Nullable] public string    RMemo                  { get; set; } // text(0)
		[Column,      Nullable] public double?   RAnzRudererBoot        { get; set; } // Double
		[Column,      Nullable] public string    RLaufTyp               { get; set; } // text(4)
		[Column,      Nullable] public double?   RRennTyp               { get; set; } // Double
		[Column,      Nullable] public string    RLaufTypGenerell       { get; set; } // text(50)
		[Column,      Nullable] public int?      RGewichtsklassenID     { get; set; } // Long
		[Column,      Nullable] public int?      RAltersklassenID       { get; set; } // Long
		[Column,      Nullable] public int?      RBootsklassenID        { get; set; } // Long
		[Column,      Nullable] public string    RZusatz                { get; set; } // text(50)
		[Column,      Nullable] public int?      RAltersklassenZusatzID { get; set; } // Long
	}

	// View
	[Table("AVereinNamen")]
	public partial class AVereinNaman
	{
		[Column, Nullable] public int?    VID     { get; set; } // Long
		[Column, Nullable] public string  NL      { get; set; } // text(255)
		[Column, Nullable] public string  NK      { get; set; } // text(255)
		[Column, Nullable] public double? VRabatt { get; set; } // Double
	}

	[Table("Einfügefehler")]
	public partial class Einfügefehler
	{
		[Column, Nullable] public string Feld0  { get; set; } // text(0)
		[Column, Nullable] public string Feld1  { get; set; } // text(0)
		[Column, Nullable] public string Feld2  { get; set; } // text(0)
		[Column, Nullable] public string Feld3  { get; set; } // text(0)
		[Column, Nullable] public string Feld4  { get; set; } // text(0)
		[Column, Nullable] public string Feld5  { get; set; } // text(0)
		[Column, Nullable] public string Feld6  { get; set; } // text(0)
		[Column, Nullable] public string Feld7  { get; set; } // text(0)
		[Column, Nullable] public string Feld8  { get; set; } // text(0)
		[Column, Nullable] public string Feld9  { get; set; } // text(0)
		[Column, Nullable] public string Feld10 { get; set; } // text(0)
		[Column, Nullable] public string Feld11 { get; set; } // text(0)
	}

	[Table("TAbmeldung")]
	public partial class TAbmeldung
	{
		[PrimaryKey, Identity] public int    ID        { get; set; } // Long
		[Column,     Nullable] public string Zeit      { get; set; } // text(255)
		[Column,     Nullable] public string StartNr   { get; set; } // text(3)
		[Column,     Nullable] public string RennNr    { get; set; } // text(6)
		[Column,     Nullable] public char?  AbtNr     { get; set; } // text(1)
		[Column,     Nullable] public char?  Start     { get; set; } // text(1)
		[Column,     Nullable] public int?   Schiri    { get; set; } // Long
		[Column,     Nullable] public int?   Bem       { get; set; } // Long
		[Column,     Nullable] public string Bemerkung { get; set; } // text(255)
	}

	[Table("TAbteilungstext")]
	public partial class TAbteilungstext
	{
		[PrimaryKey, Nullable] public char?  AID   { get; set; } // text(1)
		[Column,     Nullable] public string AText { get; set; } // text(50)
	}

	[Table("TAltersklassen")]
	public partial class TAltersklassen
	{
		[PrimaryKey, Identity] public int    Index               { get; set; } // Long
		[Column,     Nullable] public string AltersklasseK       { get; set; } // text(8)
		[Column,     Nullable] public string AltersklasseL       { get; set; } // text(25)
		[Column,     Nullable] public string Altersklassenzusatz { get; set; } // text(8)
	}

	[Table("TAltersklassenzusatz")]
	public partial class TAltersklassenzusatz
	{
		[PrimaryKey, Identity] public int    TAZID     { get; set; } // Long
		[Column,     Nullable] public string TAZBezAnz { get; set; } // text(50)
		[Column,     Nullable] public string TAZBezGK  { get; set; } // text(50)
		[Column,     Nullable] public string TAZBezK   { get; set; } // text(50)
		[Column,     Nullable] public string TAZBezL   { get; set; } // text(50)
	}

	[Table("TBoote")]
	public partial class TBoote
	{
		[PrimaryKey, Identity] public int       BID           { get; set; } // Long
		[Column,     Nullable] public int?      BRNr          { get; set; } // Long
		[Column,     Nullable] public int?      BVID          { get; set; } // Long
		[Column,     Nullable] public string    BSNr          { get; set; } // text(3)
		[Column,     Nullable] public double?   BVNr          { get; set; } // Double
		[Column,     Nullable] public int?      BName1        { get; set; } // Long
		[Column,     Nullable] public int?      BName2        { get; set; } // Long
		[Column,     Nullable] public int?      BName3        { get; set; } // Long
		[Column,     Nullable] public int?      BName4        { get; set; } // Long
		[Column,     Nullable] public int?      BName5        { get; set; } // Long
		[Column,     Nullable] public int?      BName6        { get; set; } // Long
		[Column,     Nullable] public int?      BName7        { get; set; } // Long
		[Column,     Nullable] public int?      BName8        { get; set; } // Long
		[Column,     Nullable] public int?      BName9        { get; set; } // Long
		[Column,     Nullable] public byte?     BemK          { get; set; } // Byte
		[Column,     Nullable] public string    Bemerkung     { get; set; } // text(250)
		[Column,     Nullable] public char?     AK            { get; set; } // text(1)
		[Column,     Nullable] public string    Lgr           { get; set; } // text(3)
		[Column,     Nullable] public string    LK            { get; set; } // text(5)
		[            Identity] public bool      BPortal       { get; set; } // Bit
		[Column,     Nullable] public DateTime? BDate         { get; set; } // DateTime
		[Column,     Nullable] public string    BSpezi        { get; set; } // text(50)
		[Column,     Nullable] public string    BZusatz       { get; set; } // text(50)
		[Column,     Nullable] public string    BMNr          { get; set; } // text(50)
		[Column,     Nullable] public string    BAMeldungZu   { get; set; } // text(50)
		[Column,     Nullable] public int?      BObmann       { get; set; } // Long
		[Column,     Nullable] public string    BParameter    { get; set; } // text(50)
		[Column,     Nullable] public string    BParameterTyp { get; set; } // text(50)
	}

	[Table("TBootsklasse")]
	public partial class TBootsklasse
	{
		[PrimaryKey, Identity] public int     Index        { get; set; } // Long
		[Column,     Nullable] public string  BootsklK     { get; set; } // text(3)
		[Column,     Nullable] public string  BootsklL     { get; set; } // text(20)
		[Column,     Nullable] public double? BootsRuderer { get; set; } // Double
	}

	[Table("TGewichtsklassen")]
	public partial class TGewichtsklassen
	{
		[PrimaryKey, Identity] public int    Index            { get; set; } // Long
		[Column,     Nullable] public string GewichtsklasseK  { get; set; } // text(8)
		[Column,     Nullable] public string GewichtsklasseL  { get; set; } // text(25)
		[Column,     Nullable] public string GewichtsklasseGK { get; set; } // text(50)
	}

	[Table("TIndizes")]
	public partial class TIndize
	{
		[PrimaryKey, Identity] public int    Index        { get; set; } // Long
		[Column,     Nullable] public string Tabellenname { get; set; } // text(200)
		[Column,     Nullable] public int?   lastIndex    { get; set; } // Long
	}

	[Table("TLänder")]
	public partial class TLänder
	{
		[PrimaryKey, Nullable] public string LandK { get; set; } // text(3)
		[Column,     Nullable] public string Land  { get; set; } // text(50)
	}

	[Table("TLauftyptext")]
	public partial class TLauftyptext
	{
		[Column, Nullable] public char?  LNr      { get; set; } // text(1)
		[Column, Nullable] public string LLaufTyp { get; set; } // text(4)
		[Column, Nullable] public string LText    { get; set; } // text(50)
	}

	[Table("TRennen")]
	public partial class TRennen
	{
		[PrimaryKey, Identity] public int       Index                  { get; set; } // Long
		[Column,     Nullable] public int?      RRF                    { get; set; } // Long
		[Column,     Nullable] public string    RNr                    { get; set; } // text(6)
		[Column,     Nullable] public string    RKBez                  { get; set; } // text(50)
		[Column,     Nullable] public string    RLBez                  { get; set; } // text(75)
		[Column,     Nullable] public string    RLänge                 { get; set; } // text(6)
		[Column,     Nullable] public byte?     RStartplaetze          { get; set; } // Byte
		[Column,     Nullable] public decimal?  RMeldGeld              { get; set; } // Currency
		[Column,     Nullable] public DateTime? RZeit                  { get; set; } // DateTime
		[Column,     Nullable] public string    RTag                   { get; set; } // text(2)
		[Column,     Nullable] public short?    RBootAnz               { get; set; } // Short
		[            Identity] public bool      RNotProtokoll          { get; set; } // Bit
		[Column,     Nullable] public string    RSpenden               { get; set; } // text(250)
		[Column,     Nullable] public string    RMemo                  { get; set; } // text(0)
		[Column,     Nullable] public double?   RAnzRudererBoot        { get; set; } // Double
		[Column,     Nullable] public string    RLaufTyp               { get; set; } // text(4)
		[Column,     Nullable] public double?   RRennTyp               { get; set; } // Double
		[Column,     Nullable] public string    RLaufTypGenerell       { get; set; } // text(50)
		[Column,     Nullable] public int?      RGewichtsklassenID     { get; set; } // Long
		[Column,     Nullable] public int?      RAltersklassenID       { get; set; } // Long
		[Column,     Nullable] public int?      RBootsklassenID        { get; set; } // Long
		[Column,     Nullable] public string    RZusatz                { get; set; } // text(50)
		[Column,     Nullable] public int?      RAltersklassenZusatzID { get; set; } // Long
		[Column,     Nullable] public string    Lgr                    { get; set; } // text(3)
	}

	[Table("TRuderer")]
	public partial class TRuderer
	{
		[PrimaryKey, Nullable] public int?    RID             { get; set; } // Long
		[Column,     Nullable] public string  RName           { get; set; } // text(50)
		[Column,     Nullable] public string  RVorname        { get; set; } // text(50)
		[Column,     Nullable] public double? RJg             { get; set; } // Double
		[Column,     Nullable] public int?    RVerein         { get; set; } // Long
		[Column,     Nullable] public double? GewSa           { get; set; } // Double
		[Column,     Nullable] public double? GewSo           { get; set; } // Double
		[Column,     Nullable] public short?  Bem             { get; set; } // Short
		[Column,     Nullable] public string  Bemerkung       { get; set; } // text(50)
		[Column,     Nullable] public string  AktivenPassID   { get; set; } // text(11)
		[Column,     Nullable] public char?   Geschlecht      { get; set; } // text(1)
		[Identity            ] public int     Startberechtigt { get; set; } // Long
		[Column,     Nullable] public int?    HoeherStart     { get; set; } // Long
		[Column,     Nullable] public string  Lgr             { get; set; } // text(3)
	}

	// View
	[Table("TTest_deleteme")]
	public partial class TTest_deleteme
	{
		[Column, Nullable] public int?    RID             { get; set; } // Long
		[Column, Nullable] public string  RName           { get; set; } // text(50)
		[Column, Nullable] public string  RVorname        { get; set; } // text(50)
		[Column, Nullable] public double? RJg             { get; set; } // Double
		[Column, Nullable] public int?    RVerein         { get; set; } // Long
		[Column, Nullable] public double? GewSa           { get; set; } // Double
		[Column, Nullable] public double? GewSo           { get; set; } // Double
		[Column, Nullable] public short?  Bem             { get; set; } // Short
		[Column, Nullable] public string  Bemerkung       { get; set; } // text(50)
		[Column, Nullable] public string  AktivenPassID   { get; set; } // text(11)
		[Column, Nullable] public char?   Geschlecht      { get; set; } // text(1)
		[Column, Nullable] public int?    Startberechtigt { get; set; } // Long
		[Column, Nullable] public int?    HoeherStart     { get; set; } // Long
		[Column, Nullable] public string  Lgr             { get; set; } // text(3)
	}

	[Table("TVerein")]
	public partial class TVerein
	{
		[PrimaryKey, Identity   ] public int     VIDVerein         { get; set; } // Long
		[Column,        Nullable] public string  VVereinsName      { get; set; } // text(255)
		[Column,        Nullable] public string  VVereinsnamenKurz { get; set; } // text(255)
		[Column,        Nullable] public string  VKurzzeichen      { get; set; } // text(255)
		[Column,        Nullable] public double? VRabatt           { get; set; } // Double
		[Column,     NotNull    ] public string  VUnterverein      { get; set; } // text(70)
		[Column,        Nullable] public int?    VAnzUVs           { get; set; } // Long
		[Column,        Nullable] public string  VStadt            { get; set; } // text(150)
		[Column,        Nullable] public string  VObmann           { get; set; } // text(50)
		[Column,        Nullable] public string  VStraße           { get; set; } // text(50)
		[Column,        Nullable] public string  VPLZ              { get; set; } // text(5)
		[Column,        Nullable] public string  VOrt              { get; set; } // text(255)
		[Column,        Nullable] public string  VLand             { get; set; } // text(5)
		[Column,        Nullable] public string  VTel              { get; set; } // text(14)
		[Column,        Nullable] public string  VFax              { get; set; } // text(14)
	}

	public static partial class TableExtensions
	{
		public static TAbmeldung Find(this ITable<TAbmeldung> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static TAbteilungstext Find(this ITable<TAbteilungstext> table, char? AID)
		{
			return table.FirstOrDefault(t =>
				t.AID == AID);
		}

		public static TAltersklassen Find(this ITable<TAltersklassen> table, int Index)
		{
			return table.FirstOrDefault(t =>
				t.Index == Index);
		}

		public static TAltersklassenzusatz Find(this ITable<TAltersklassenzusatz> table, int TAZID)
		{
			return table.FirstOrDefault(t =>
				t.TAZID == TAZID);
		}

		public static TBoote Find(this ITable<TBoote> table, int BID)
		{
			return table.FirstOrDefault(t =>
				t.BID == BID);
		}

		public static TBootsklasse Find(this ITable<TBootsklasse> table, int Index)
		{
			return table.FirstOrDefault(t =>
				t.Index == Index);
		}

		public static TGewichtsklassen Find(this ITable<TGewichtsklassen> table, int Index)
		{
			return table.FirstOrDefault(t =>
				t.Index == Index);
		}

		public static TIndize Find(this ITable<TIndize> table, int Index)
		{
			return table.FirstOrDefault(t =>
				t.Index == Index);
		}

		public static TLänder Find(this ITable<TLänder> table, string LandK)
		{
			return table.FirstOrDefault(t =>
				t.LandK == LandK);
		}

		public static TRennen Find(this ITable<TRennen> table, int Index)
		{
			return table.FirstOrDefault(t =>
				t.Index == Index);
		}

		public static TRuderer Find(this ITable<TRuderer> table, int? RID)
		{
			return table.FirstOrDefault(t =>
				t.RID == RID);
		}

		public static TVerein Find(this ITable<TVerein> table, int VIDVerein)
		{
			return table.FirstOrDefault(t =>
				t.VIDVerein == VIDVerein);
		}
	}
}
