//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.8935
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=2.0.50727.3038.
// 
namespace Mrv.Regatta.Waage.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Messung {
        
        private int idField;
        
        private string nameField;
        
        private float gewichtField;
        
        private System.DateTime zeitstempelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Gewicht {
            get {
                return this.gewichtField;
            }
            set {
                this.gewichtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Zeitstempel {
            get {
                return this.zeitstempelField;
            }
            set {
                this.zeitstempelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Einstellungen {
        
        private CT_Renntag[] renntageField;
        
        private CT_Pfade pfadeField;
        
        private EinstellungenPersonenListe personenListeField;
        
        private System.DateTime zeitstempelHeuteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Renntag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CT_Renntag[] Renntage {
            get {
                return this.renntageField;
            }
            set {
                this.renntageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CT_Pfade Pfade {
            get {
                return this.pfadeField;
            }
            set {
                this.pfadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EinstellungenPersonenListe PersonenListe {
            get {
                return this.personenListeField;
            }
            set {
                this.personenListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ZeitstempelHeute {
            get {
                return this.zeitstempelHeuteField;
            }
            set {
                this.zeitstempelHeuteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Renntag {
        
        private string wochentagField;
        
        private System.DateTime datumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Wochentag {
            get {
                return this.wochentagField;
            }
            set {
                this.wochentagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Pfade {
        
        private string regelnField;
        
        private string rennenField;
        
        private string messungenField;
        
        private string logdateiField;
        
        private string backupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Regeln {
            get {
                return this.regelnField;
            }
            set {
                this.regelnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rennen {
            get {
                return this.rennenField;
            }
            set {
                this.rennenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Messungen {
            get {
                return this.messungenField;
            }
            set {
                this.messungenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Logdatei {
            get {
                return this.logdateiField;
            }
            set {
                this.logdateiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Backups {
            get {
                return this.backupsField;
            }
            set {
                this.backupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum EinstellungenPersonenListe {
        
        /// <remarks/>
        Alle,
        
        /// <remarks/>
        Regatta,
        
        /// <remarks/>
        Leichtgewichte,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Regeln {
        
        private CT_Regel[] regelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Regel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CT_Regel[] Regel {
            get {
                return this.regelField;
            }
            set {
                this.regelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Regel {
        
        private CT_Bedingung[] ifField;
        
        private CT_Bedingung[] ifNotField;
        
        private CT_RennInfo rennInfoField;
        
        private bool aktivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("If", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CT_Bedingung[] If {
            get {
                return this.ifField;
            }
            set {
                this.ifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IfNot", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CT_Bedingung[] IfNot {
            get {
                return this.ifNotField;
            }
            set {
                this.ifNotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CT_RennInfo RennInfo {
            get {
                return this.rennInfoField;
            }
            set {
                this.rennInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Aktiv {
            get {
                return this.aktivField;
            }
            set {
                this.aktivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Bedingung {
        
        private string regExField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegEx {
            get {
                return this.regExField;
            }
            set {
                this.regExField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_RennInfo {
        
        private float einzelgewichtField;
        
        private bool einzelgewichtFieldSpecified;
        
        private float durchschnittsgewichtField;
        
        private bool durchschnittsgewichtFieldSpecified;
        
        private float gewichtSteuermannField;
        
        private bool gewichtSteuermannFieldSpecified;
        
        private bool kinderrennenField;
        
        private bool kinderrennenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Einzelgewicht {
            get {
                return this.einzelgewichtField;
            }
            set {
                this.einzelgewichtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EinzelgewichtSpecified {
            get {
                return this.einzelgewichtFieldSpecified;
            }
            set {
                this.einzelgewichtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Durchschnittsgewicht {
            get {
                return this.durchschnittsgewichtField;
            }
            set {
                this.durchschnittsgewichtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DurchschnittsgewichtSpecified {
            get {
                return this.durchschnittsgewichtFieldSpecified;
            }
            set {
                this.durchschnittsgewichtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float GewichtSteuermann {
            get {
                return this.gewichtSteuermannField;
            }
            set {
                this.gewichtSteuermannField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GewichtSteuermannSpecified {
            get {
                return this.gewichtSteuermannFieldSpecified;
            }
            set {
                this.gewichtSteuermannFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Kinderrennen {
            get {
                return this.kinderrennenField;
            }
            set {
                this.kinderrennenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KinderrennenSpecified {
            get {
                return this.kinderrennenFieldSpecified;
            }
            set {
                this.kinderrennenFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Rennen {
        
        private RennenRennen[] rennen1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rennen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RennenRennen[] Rennen1 {
            get {
                return this.rennen1Field;
            }
            set {
                this.rennen1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RennenRennen {
        
        private CT_RennInfo rennInfoField;
        
        private bool aktivField;
        
        private string rennNrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CT_RennInfo RennInfo {
            get {
                return this.rennInfoField;
            }
            set {
                this.rennInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Aktiv {
            get {
                return this.aktivField;
            }
            set {
                this.aktivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RennNr {
            get {
                return this.rennNrField;
            }
            set {
                this.rennNrField = value;
            }
        }
    }
}
